version: '3.8'
services:
  backend:
    build:
      context: ./student_api
    container_name: student_api
    ports:
      - 8000:8000
    networks:
      - mine  

  db:
    image: postgres
    environment:
       POSTGRES_DB: app
       POSTGRES_USER: app
       POSTGRES_PASSWORD: password
       POSTGRES_SERVER: db
    ports:
      - 5000:5432 
    networks:
      - mine   
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mine

networks:
  mine:
    driver: bridge        